### ISSUE TITLE
Give online

### ISSUE THREAD

**Issue by marioded** [Fabrimat/MinecraftITALIA-Rewards#1]
Sarebbe carino se si potesse fare una opzione nel config es. give-all-online in modo invece di riscattarli manualmente tramite la GUI, la GUI non ci sia più e, arrivati ad esempio tot voti a tutti gli online nel server da il reward impostato nel config

**Comment by Fabrimat** [comment]
Quindi il premio sarebbe dato solo alle persone online a mezzanotte?
Mi sembra un po' troppo estremo

**Comment by marioded** [comment]
> Quindi il premio sarebbe dato solo alle persone online a mezzanotte?
> Mi sembra un po' troppo estremo

No, allora, ad esempio: slimecraft raggiunge 50 voti e a tutti quelli online in QUEL MOMENTO da il premio, chi c'è c'è, chi non c'è, non c'è

**Comment by Fabrimat** [comment]
Quel momento sarebbe mezzanotte.

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
> > Quindi il premio sarebbe dato solo alle persone online a mezzanotte?
> > Mi sembra un po' troppo estremo
> 
> No, allora, ad esempio: slimecraft raggiunge 50 voti e a tutti quelli online in QUEL MOMENTO da il premio, chi c'è c'è, chi non c'è, non c'è

Mi sembra troppo estremo.
_Se io voto il server alle 20h perché son tornato da scuola e ho finito i compiti e poi dopo mia mamma mi dice che devo andare a dormire perché l'indomani ho il compito di geometria e non posso aspettare la mezzanotte.... mi sembra ridicolo che non possa essere premiato. a questo punto non mi interessa più votare il server, tanto a che pro?_

Devi pensare come penserebbe un utente... cercando di capire anche le sue esigenze. Poi voglio dire... immagina anche che hai tutto il giorno il server completamente vuoto, poi hai il boom di ingressi alle 23h30 in attesa del reward a mezzanotte.... metti che ti crasha il server per connection trottled?

**Comment by marioded** [comment]
La mia mente non pensava che i voti vengono calcolati alle 0:00, per me ogni ad esempio 2 min venivano aggiornati.
